language: python
python:
- '2.7'
script:
- python setup.py test
install:
- pip install .
- pip install -r requirements.txt
deploy:
  provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: khfayzullaev
  password:
    secure: WSmTqTSmfb7kEorwO3gvN+fOV+pYgxHW73nJ7/+NlXKG2fY3q9VJFy13XNH0aHMGeazM3tv0W6b3DuPHm7WdgFrWKi4uv6uod9CxhjROHO6dWYovyd7spVp5NvfEfsb5bCn89Qd2IEBhRFFkLXF+KhXWXa+KvEmO0XDg0F8FtNB4FMceuwdNns4yZISK9toiei3rE0JXKdn3ca+Fo4htzx/0Wt4Or4gHLMJ0gEIc5wjorAYpCr9lq93f7IWFXvRCTLznbeYZMDe/zNcdbNEPc42soPQUIjfEK3bukgb0xEnkaNgFG8nuDErQzV2fG0nwmv4ryr30vFNXqmgVy7qD1CcTrX7eUMUbqXohihmLfiJtkpKu6847Rf7IVtlnZDGODSqNMwRcOa0Tr9tql5soIQb3UC82sNKA3PkHxz8AdO9p5f6JasJYN10/hbje85vVmgV4OaxwN88DL23AuvAQt0Hts+UlTIU762PFEAUYITWflS8zfMFGQVeArF2qPICEQpo67l83bk/3nlQ871ZjlHIHUQgVOW5q34FXHfj7IwP9fnNU0AYbddnxeU9AHp3FQ2VpYNH9zT3+p2sosldQqgUcwUiZLYYcMo9evC3Qhm4sgTkjgXheFZ8sJYZ74t2Jc9c0oa5XqhdeIM+qoUpNc+/a6rtcrGbBnOu14EK94Ok=
  on:
    tags: false
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
before_install:
- openssl aes-256-cbc -K $encrypted_f16542cddf46_key -iv $encrypted_f16542cddf46_iv
  -in config.ini.enc -out zype/tests/config.ini -d
