language: python
python:
- '2.7'
script:
- python setup.py test
install:
- pip install .
- pip install -r requirements.txt
deploy:
  provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: REPLACE_ME
  password:
    secure: REPLACE_ME
  on:
    tags: false
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
before_install:
- openssl aes-256-cbc -K $REPLACE_ME -iv $REPLACE_ME
  -in config.ini.enc -out zype/tests/config.ini -d
